import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create schema auth; create table auth.users(id uuid primary key);
  create role anon; create role authenticated;
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid$$;`);
await db.exec(readFileSync(new URL('../schema.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../migrations/20260929_product_controls.sql', import.meta.url), 'utf8'));
await db.exec(readFileSync(new URL('../migrations/20260929_product_controls.sql', import.meta.url), 'utf8'));
const admin = randomUUID(), staff = randomUUID(), outsider = randomUUID(), workspace = randomUUID(), other = randomUUID(), pid = randomUUID();
await db.query('insert into auth.users values ($1), ($2), ($3)', [admin, staff, outsider]);
await db.query("insert into public.workspaces values ($1,'Test'),($2,'Other')", [workspace, other]);
await db.query("insert into public.profiles(id,workspace_id,name,role) values ($1,$4,'Admin','admin'),($2,$4,'Staff','staff'),($3,$5,'Other','admin')", [admin,staff,outsider,workspace,other]);
const login = async id => { await db.exec('reset role'); await db.query("select set_config('request.jwt.claim.sub', $1, false)", [id]); await db.exec('set role authenticated'); };
const apply = op => db.query('select public.apply_operation($1::jsonb)', [JSON.stringify(op)]);
const snapshot = async () => (await db.query('select public.inventory_snapshot() as data')).rows[0].data;
const event = (actor, delta, kind) => ({id:randomUUID(), productId:pid, productName:'Untrusted name', actorId:actor,actorName:'FORGED',delta,valueDelta:999,kind,note:'Test',at:new Date().toISOString()});
const product = {id:pid,name:'Kahve',sku:'K01',category:'Gıda',unit:'adet',cost:10,threshold:3,createdAt:new Date().toISOString()};
await login(admin);
const createEvent = event(admin,0,'create');
const create = {id:createEvent.id,actorId:admin,type:'product',product,event:createEvent,expectedRevision:null};
await apply(create); await apply(create);
assert.equal((await snapshot()).events.length,1);
console.log('PASS schema, authenticated RPC, idempotent retry');
const incoming = event(admin,10,'in');
await apply({id:incoming.id,actorId:admin,type:'movement',event:incoming});
let state = await snapshot();
assert.equal(state.events.find(e=>e.id===incoming.id).valueDelta,100);
assert.equal(state.events.find(e=>e.id===incoming.id).actorName,'Admin');
await login(staff);
const deniedIn = event(staff,2,'in');
await assert.rejects(apply({id:deniedIn.id,actorId:staff,type:'movement',event:deniedIn}), /yalnızca admin/);
const staffOut = event(staff,-2,'out');
await apply({id:staffOut.id,actorId:staff,type:'movement',event:staffOut});
assert.equal((await snapshot()).events.find(e=>e.id===staffOut.id).actorName,'Staff');
const forbiddenEdit = event(staff,0,'edit');
await assert.rejects(apply({id:forbiddenEdit.id,actorId:staff,type:'product',product,event:forbiddenEdit,expectedRevision:createEvent.id}), /Yönetici/);
await assert.rejects(db.query("update public.profiles set role='admin' where id=$1",[staff]));
await assert.rejects(db.query('delete from public.stock_events'));
console.log('PASS staff movement, authoritative actor and cost, direct-write denial');
const outgoing = event(staff,-11,'out');
await assert.rejects(apply({id:outgoing.id,actorId:staff,type:'movement',event:outgoing}), /yeterli stok/);
assert.equal((await snapshot()).events.length,3);
console.log('PASS insufficient stock rejects atomically');
await login(admin);
const edited = event(admin,0,'edit');
await apply({id:edited.id,actorId:admin,type:'product',event:edited,product:{...product,cost:20},expectedRevision:createEvent.id});
state = await snapshot();
assert.equal(state.events.find(e=>e.id===edited.id).valueDelta,80);
assert.equal(state.products[0].revision, edited.id);
const stale = event(admin,0,'edit');
await assert.rejects(apply({id:stale.id,actorId:admin,type:'product',event:stale,product,expectedRevision:createEvent.id}), /başka cihazda/);
console.log('PASS cost revaluation and stale metadata conflict');
const changedUnit = event(admin,0,'edit');
await assert.rejects(apply({id:changedUnit.id,actorId:admin,type:'product',event:changedUnit,product:{...state.products[0],unit:'kg'},expectedRevision:edited.id}), /Stok varken/);
const freeze = event(admin,0,'edit');
await apply({id:freeze.id,actorId:admin,type:'product',event:freeze,product:{...state.products[0],isFrozen:true,adminMessage:'Bu ürünü kullanmayın'},expectedRevision:edited.id});
for (const actor of [staff,admin]) {
  await login(actor);
  for (const delta of [-1,1]) {
    const blocked=event(actor,delta,delta>0?'in':'out');
    await assert.rejects(apply({id:blocked.id,actorId:actor,type:'movement',event:blocked}), /donduruldu/);
  }
  assert.equal((await snapshot()).products[0].adminMessage,'Bu ürünü kullanmayın');
}
// A legacy admin client without control fields cannot silently clear a freeze.
const legacyEdit = event(admin,0,'edit');
await apply({id:legacyEdit.id,actorId:admin,type:'product',event:legacyEdit,product,expectedRevision:freeze.id});
assert.equal((await snapshot()).products[0].isFrozen,true);
const unfreeze=event(admin,0,'edit');
await apply({id:unfreeze.id,actorId:admin,type:'product',event:unfreeze,product:{...(await snapshot()).products[0],isFrozen:false},expectedRevision:legacyEdit.id});
await login(staff);
const resumed=event(staff,-1,'out');
await apply({id:resumed.id,actorId:staff,type:'movement',event:resumed});
assert.equal((await snapshot()).products[0].isFrozen,false);
console.log('PASS frozen stock for both roles, legacy preservation, admin unfreeze, unit protection');
await login(outsider);
assert.deepEqual(await snapshot(), {products:[],events:[]});
const foreignEvent = event(outsider,1,'in');
await assert.rejects(apply({id:foreignEvent.id,actorId:outsider,type:'movement',event:foreignEvent}), /Ürün bulunamadı/);
console.log('PASS workspace isolation');
await db.exec('reset role');
await db.query('update public.profiles set active=false where id=$1',[staff]);
await login(staff);
await assert.rejects(snapshot(),/Aktif/);
console.log('PASS revoked membership');
await db.close();

